import * as XLSX from "xlsx";

import {
  CLAIM_LABEL,
  CONFIDENCE_LABEL,
  PROFESSIONAL_REVIEW_DISCLAIMER,
  SEVERITY_LABEL,
  fmtDateTime,
  humanizeAction,
  type ExportPayload,
} from "@/lib/export/types";

/**
 * XLSX export (PRD §24).
 *
 * A spreadsheet is what an auditor actually re-works in, so tables become real sheets with real
 * numbers — not text. The Provenance sheet leads because a workbook detaches from the platform
 * the moment it is downloaded: whoever opens it later must still be able to see which model,
 * prompt version and revision produced it, and that it is not a signed opinion.
 */
export function renderAuditXlsx(payload: ExportPayload): Buffer {
  const wb = XLSX.utils.book_new();
  const { audit, provenance, organisation } = payload;

  const provenanceRows: (string | number | null)[][] = [
    ["Audit", audit.name],
    ["Organisation", organisation.name],
    ...(payload.client ? [["Client", payload.client.name]] : []),
    ["Objective", audit.objective ?? ""],
    ["Period", audit.periodLabel ?? [audit.periodStart, audit.periodEnd].filter(Boolean).join(" to ")],
    ["Entity", audit.entityName ?? "Not specified"],
    ["Overall risk", audit.overallRisk ?? "Not assessed"],
    ["Revision", provenance.revisionNumber],
    ["Revision status", provenance.revisionStatus],
    ["Model", provenance.modelId ?? "Not recorded"],
    ["Prompt version", provenance.promptVersion ?? "Not recorded"],
    ["Block schema version", provenance.schemaVersion ?? "Not recorded"],
    ["Template", provenance.templateName ? `${provenance.templateName} v${provenance.templateVersion ?? 1}` : "None"],
    ["Generated", fmtDateTime(provenance.generatedAt)],
    ["Generated by", provenance.generatedByEmail ?? ""],
    ["Quality review passed", provenance.qualityPassed === null ? "Not run" : provenance.qualityPassed ? "Yes" : "No"],
    ["Quality score", provenance.qualityScore],
    [],
    [PROFESSIONAL_REVIEW_DISCLAIMER.heading],
    ...PROFESSIONAL_REVIEW_DISCLAIMER.body.map((line) => [line]),
  ];
  addSheet(wb, "Provenance", provenanceRows, [24, 90]);

  addSheet(
    wb,
    "Findings",
    [
      [
        "Ref",
        "Title",
        "Severity",
        "Confidence",
        "Claim type",
        "Risk category",
        "Status",
        "Financial impact",
        "Currency",
        "Impact basis",
        "Summary",
        "Detail",
        "Recommended follow-up",
        "Recommended remediation",
        "Management response",
        "Affected periods",
        "Affected entities",
        "Affected accounts",
        "Evidence",
      ],
      ...payload.findings.map((f) => [
        f.key,
        f.title,
        SEVERITY_LABEL[f.severity],
        CONFIDENCE_LABEL[f.confidence],
        CLAIM_LABEL[f.claimType],
        f.riskCategory,
        f.status,
        // A real number, so it sums in the sheet rather than sitting there as text.
        f.financialImpact,
        f.financialImpactCurrency ?? "",
        f.impactBasis ?? "",
        f.summary,
        f.detail,
        f.recommendedFollowup ?? "",
        f.recommendedRemediation ?? "",
        f.managementResponse ?? "",
        f.affectedPeriods.join("; "),
        f.affectedEntities.join("; "),
        f.affectedAccounts.join("; "),
        payload.evidence
          .filter((e) => e.findingId === f.id)
          .map((e) => `${e.label}${e.locatorText ? ` (${e.locatorText})` : ""}`)
          .join(" | "),
      ]),
    ],
    [10, 46, 12, 12, 20, 22, 12, 16, 10, 40, 60, 80, 50, 50, 40, 20, 20, 20, 60],
  );

  // Each table block becomes its own sheet: that is the whole reason to export XLSX.
  let tableIndex = 0;
  for (const block of payload.blocks) {
    if (!block.block) continue;
    const value = block.block;
    if (!("data" in value) || !value.data || typeof value.data !== "object" || !("columns" in value.data)) {
      continue;
    }
    const data = value.data as {
      columns: { label: string }[];
      rows: (string | number | boolean | null)[][];
      totalRow?: (string | number | boolean | null)[] | null;
    };
    tableIndex += 1;
    const name = sheetName(block.title, `Table ${tableIndex}`);
    addSheet(wb, name, [
      [block.title],
      [],
      data.columns.map((c) => c.label),
      ...data.rows,
      ...(data.totalRow ? [data.totalRow] : []),
    ]);
  }

  if (payload.options.includeEvidence && payload.evidence.length > 0) {
    addSheet(
      wb,
      "Evidence",
      [
        ["Label", "Location", "Excerpt", "Input", "Input kind", "File", "Checksum"],
        ...payload.evidence.map((e) => [
          e.label,
          e.locatorText,
          e.excerpt ?? "",
          e.inputName,
          e.inputKind,
          e.inputFileName ?? "",
          e.inputChecksum ?? "",
        ]),
      ],
      [40, 28, 70, 30, 12, 30, 66],
    );
  }

  if (payload.options.includeInputList && payload.inputs.length > 0) {
    addSheet(
      wb,
      "Inputs",
      [
        ["Name", "Kind", "Status", "File", "Size", "Rows", "Detected periods", "Currencies", "Entities", "Warnings"],
        ...payload.inputs.map((i) => [
          i.name,
          i.kind,
          i.status,
          i.fileName ?? "",
          i.fileSize,
          i.rowCount,
          i.periods.join("; ") || "Not determined",
          i.currencies.join("; ") || "Not determined",
          i.entities.join("; ") || "Not determined",
          i.warnings.map((w) => w.message).join(" | "),
        ]),
      ],
      [40, 12, 12, 34, 10, 8, 30, 18, 24, 60],
    );
  }

  if (payload.options.includeInstructions && payload.instructions.length > 0) {
    addSheet(
      wb,
      "Instructions",
      [
        ["#", "Name", "Source", "Mandatory", "Version", "Text"],
        ...payload.instructions.map((i, n) => [
          n + 1,
          i.name,
          i.source,
          i.mandatory ? "Yes" : "No",
          i.version ?? "",
          i.text,
        ]),
      ],
      [5, 40, 24, 11, 9, 120],
    );
  }

  if (payload.options.includeActivity && payload.activity.length > 0) {
    addSheet(
      wb,
      "Activity",
      [
        ["When", "Who", "Action", "Target"],
        ...payload.activity.map((a) => [
          fmtDateTime(a.at),
          a.actorEmail ?? "System",
          humanizeAction(a.action),
          a.targetType ?? "",
        ]),
      ],
      [24, 34, 34, 20],
    );
  }

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

/** Excel rejects >31 chars and the characters below, and silently mangles duplicates. */
function sheetName(raw: string, fallback: string): string {
  const cleaned = raw.replace(/[[\]:*?/\\]/g, " ").trim();
  return (cleaned || fallback).slice(0, 31);
}

function addSheet(
  wb: XLSX.WorkBook,
  name: string,
  rows: (string | number | boolean | null | undefined)[][],
  widths?: number[],
) {
  const sheet = XLSX.utils.aoa_to_sheet(rows.map((row) => row.map((c) => (c === undefined ? null : c))));
  if (widths) sheet["!cols"] = widths.map((w) => ({ wch: w }));
  let unique = sheetName(name, "Sheet");
  let n = 2;
  while (wb.SheetNames.includes(unique)) {
    unique = `${sheetName(name, "Sheet").slice(0, 27)} (${n})`;
    n += 1;
  }
  XLSX.utils.book_append_sheet(wb, sheet, unique);
}
