/**
 * The integration catalog (PRD §16).
 *
 * Providers are a code constant rather than a table: the catalog ships with the app, while a
 * *connection* to one of them is tenant data. Connections are reusable, but imports are always
 * audit-scoped snapshots — the platform deliberately does not keep a synchronised global copy of
 * anyone's accounting data (PRD "Important integration behavior").
 */
export const INTEGRATION_CATEGORIES = [
  "accounting",
  "banking",
  "business",
  "data",
  "storage",
] as const;

export type IntegrationCategory = (typeof INTEGRATION_CATEGORIES)[number];

export type AuthType = "oauth2" | "api_key" | "basic" | "connection_string" | "file_transfer";

export type IntegrationProvider = {
  key: string;
  name: string;
  category: IntegrationCategory;
  description: string;
  authType: AuthType;
  /** Datasets a user can pull into an audit as a snapshot. */
  datasets: string[];
  /** Which audit domains this provider tends to feed. */
  domains: string[];
};

export const INTEGRATION_PROVIDERS: readonly IntegrationProvider[] = [
  // ── Accounting systems (§16.1) ─────────────────────────────────────────────
  {
    key: "quickbooks",
    name: "QuickBooks",
    category: "accounting",
    description: "Cloud accounting for small and mid-sized businesses.",
    authType: "oauth2",
    datasets: [
      "general_ledger",
      "trial_balance",
      "journal_entries",
      "chart_of_accounts",
      "invoices",
      "bills",
      "payments",
      "customers",
      "suppliers",
      "bank_transactions",
    ],
    domains: ["general", "ledger", "cash", "customers", "suppliers"],
  },
  {
    key: "xero",
    name: "Xero",
    category: "accounting",
    description: "Cloud accounting platform with strong bank reconciliation.",
    authType: "oauth2",
    datasets: [
      "general_ledger",
      "trial_balance",
      "journal_entries",
      "chart_of_accounts",
      "invoices",
      "bills",
      "bank_transactions",
      "budgets",
      "contacts",
    ],
    domains: ["general", "ledger", "cash", "budgets", "customers", "suppliers"],
  },
  {
    key: "sage",
    name: "Sage",
    category: "accounting",
    description: "Sage Business Cloud / Sage 50 / Sage 200 accounting.",
    authType: "oauth2",
    datasets: ["general_ledger", "trial_balance", "journal_entries", "invoices", "payments", "suppliers"],
    domains: ["general", "ledger", "suppliers"],
  },
  {
    key: "zoho_books",
    name: "Zoho Books",
    category: "accounting",
    description: "Zoho's online accounting suite.",
    authType: "oauth2",
    datasets: ["general_ledger", "trial_balance", "invoices", "bills", "expenses", "bank_transactions"],
    domains: ["general", "ledger", "cash", "customers", "suppliers"],
  },
  {
    key: "netsuite",
    name: "Oracle NetSuite",
    category: "accounting",
    description: "Cloud ERP with multi-subsidiary consolidation.",
    authType: "oauth2",
    datasets: [
      "general_ledger",
      "trial_balance",
      "journal_entries",
      "subsidiaries",
      "budgets",
      "vendor_bills",
      "customer_invoices",
      "intercompany",
    ],
    domains: ["general", "ledger", "budgets", "customers", "suppliers"],
  },
  {
    key: "dynamics365",
    name: "Microsoft Dynamics 365",
    category: "accounting",
    description: "Dynamics 365 Business Central / Finance & Operations.",
    authType: "oauth2",
    datasets: ["general_ledger", "trial_balance", "journal_entries", "dimensions", "budgets", "vendors", "customers"],
    domains: ["general", "ledger", "budgets", "customers", "suppliers"],
  },
  {
    key: "sap",
    name: "SAP",
    category: "accounting",
    description: "SAP S/4HANA and ECC finance modules.",
    authType: "basic",
    datasets: ["general_ledger", "trial_balance", "journal_entries", "cost_centers", "vendors", "customers", "assets"],
    domains: ["general", "ledger", "customers", "suppliers"],
  },
  {
    key: "oracle_fusion",
    name: "Oracle Fusion",
    category: "accounting",
    description: "Oracle Fusion Cloud ERP financials.",
    authType: "basic",
    datasets: ["general_ledger", "trial_balance", "journal_entries", "payables", "receivables"],
    domains: ["general", "ledger", "customers", "suppliers"],
  },
  {
    key: "odoo",
    name: "Odoo",
    category: "accounting",
    description: "Open-source business suite with accounting.",
    authType: "api_key",
    datasets: ["general_ledger", "journal_entries", "invoices", "bills", "payments", "analytic_accounts"],
    domains: ["general", "ledger", "customers", "suppliers"],
  },
  {
    key: "erpnext",
    name: "ERPNext",
    category: "accounting",
    description: "Open-source ERP with double-entry accounting.",
    authType: "api_key",
    datasets: ["general_ledger", "journal_entries", "invoices", "payments", "cost_centers"],
    domains: ["general", "ledger", "customers", "suppliers"],
  },
  {
    key: "custom_accounting",
    name: "Custom accounting system",
    category: "accounting",
    description: "Bring your own accounting export or API.",
    authType: "api_key",
    datasets: ["general_ledger", "trial_balance", "journal_entries", "custom"],
    domains: ["general", "ledger"],
  },

  // ── Banking (§16.2) ────────────────────────────────────────────────────────
  {
    key: "plaid",
    name: "Plaid",
    category: "banking",
    description: "Open banking aggregation across thousands of institutions.",
    authType: "oauth2",
    datasets: ["accounts", "balances", "transactions", "statements"],
    domains: ["cash"],
  },
  {
    key: "tink",
    name: "Tink",
    category: "banking",
    description: "European open banking aggregation.",
    authType: "oauth2",
    datasets: ["accounts", "balances", "transactions"],
    domains: ["cash"],
  },
  {
    key: "truelayer",
    name: "TrueLayer",
    category: "banking",
    description: "Open banking data and payments (UK/EU).",
    authType: "oauth2",
    datasets: ["accounts", "balances", "transactions"],
    domains: ["cash"],
  },
  {
    key: "bank_direct_api",
    name: "Direct bank API",
    category: "banking",
    description: "A bank's own corporate API.",
    authType: "api_key",
    datasets: ["accounts", "balances", "transactions", "statements"],
    domains: ["cash"],
  },
  {
    key: "bank_sftp",
    name: "Bank statement SFTP",
    category: "banking",
    description: "Scheduled statement drops over secure file transfer (MT940, BAI2, CAMT.053).",
    authType: "file_transfer",
    datasets: ["statements", "transactions"],
    domains: ["cash"],
  },
  {
    key: "manual_statement",
    name: "Manual statement upload",
    category: "banking",
    description: "Upload statements directly to an audit.",
    authType: "file_transfer",
    datasets: ["statements"],
    domains: ["cash"],
  },

  // ── Business systems (§16.3) ───────────────────────────────────────────────
  {
    key: "salesforce",
    name: "Salesforce",
    category: "business",
    description: "CRM opportunities, accounts and contracts.",
    authType: "oauth2",
    datasets: ["accounts", "opportunities", "contracts", "orders"],
    domains: ["customers"],
  },
  {
    key: "hubspot",
    name: "HubSpot",
    category: "business",
    description: "CRM deals and companies.",
    authType: "oauth2",
    datasets: ["companies", "deals", "line_items"],
    domains: ["customers"],
  },
  {
    key: "gusto",
    name: "Gusto",
    category: "business",
    description: "Payroll and benefits.",
    authType: "oauth2",
    datasets: ["payroll_runs", "employees", "compensation"],
    domains: ["general", "cash"],
  },
  {
    key: "adp",
    name: "ADP",
    category: "business",
    description: "Enterprise payroll.",
    authType: "oauth2",
    datasets: ["payroll_runs", "employees", "compensation"],
    domains: ["general", "cash"],
  },
  {
    key: "expensify",
    name: "Expensify",
    category: "business",
    description: "Expense reports and receipts.",
    authType: "oauth2",
    datasets: ["expense_reports", "receipts", "policies"],
    domains: ["general", "suppliers"],
  },
  {
    key: "ramp",
    name: "Ramp",
    category: "business",
    description: "Corporate cards and spend management.",
    authType: "oauth2",
    datasets: ["transactions", "reimbursements", "vendors", "limits"],
    domains: ["cash", "suppliers"],
  },
  {
    key: "brex",
    name: "Brex",
    category: "business",
    description: "Corporate cards and expense management.",
    authType: "oauth2",
    datasets: ["transactions", "expenses", "vendors"],
    domains: ["cash", "suppliers"],
  },
  {
    key: "coupa",
    name: "Coupa",
    category: "business",
    description: "Procurement, purchase orders and supplier management.",
    authType: "oauth2",
    datasets: ["purchase_orders", "invoices", "suppliers", "contracts", "receipts"],
    domains: ["suppliers"],
  },
  {
    key: "stripe",
    name: "Stripe",
    category: "business",
    description: "Payments, subscriptions and payouts.",
    authType: "api_key",
    datasets: ["charges", "refunds", "payouts", "subscriptions", "disputes", "customers"],
    domains: ["cash", "customers"],
  },
  {
    key: "adyen",
    name: "Adyen",
    category: "business",
    description: "Payment processing and settlement reports.",
    authType: "api_key",
    datasets: ["payments", "refunds", "settlements", "disputes"],
    domains: ["cash", "customers"],
  },
  {
    key: "paypal",
    name: "PayPal",
    category: "business",
    description: "Payments and settlement activity.",
    authType: "oauth2",
    datasets: ["transactions", "refunds", "settlements"],
    domains: ["cash", "customers"],
  },
  {
    key: "shopify",
    name: "Shopify",
    category: "business",
    description: "E-commerce orders, refunds and payouts.",
    authType: "oauth2",
    datasets: ["orders", "refunds", "payouts", "customers", "products"],
    domains: ["customers", "cash"],
  },
  {
    key: "woocommerce",
    name: "WooCommerce",
    category: "business",
    description: "WordPress e-commerce orders and refunds.",
    authType: "api_key",
    datasets: ["orders", "refunds", "customers"],
    domains: ["customers"],
  },
  {
    key: "chargebee",
    name: "Chargebee",
    category: "business",
    description: "Subscription billing and revenue recognition.",
    authType: "api_key",
    datasets: ["subscriptions", "invoices", "credit_notes", "revenue_recognition"],
    domains: ["customers"],
  },
  {
    key: "recurly",
    name: "Recurly",
    category: "business",
    description: "Subscription management and billing.",
    authType: "api_key",
    datasets: ["subscriptions", "invoices", "credit_notes"],
    domains: ["customers"],
  },
  {
    key: "square",
    name: "Square",
    category: "business",
    description: "Point of sale, payments and settlements.",
    authType: "oauth2",
    datasets: ["payments", "refunds", "settlements", "orders"],
    domains: ["cash", "customers"],
  },
  {
    key: "lightspeed",
    name: "Lightspeed",
    category: "business",
    description: "Retail and hospitality point of sale.",
    authType: "oauth2",
    datasets: ["sales", "refunds", "inventory"],
    domains: ["customers"],
  },
  {
    key: "cin7",
    name: "Cin7",
    category: "business",
    description: "Inventory and order management.",
    authType: "api_key",
    datasets: ["inventory", "purchase_orders", "sales_orders", "stock_movements"],
    domains: ["suppliers", "customers"],
  },

  // ── Data platforms (§16.4) ─────────────────────────────────────────────────
  {
    key: "postgres",
    name: "PostgreSQL",
    category: "data",
    description: "Query an internal Postgres database.",
    authType: "connection_string",
    datasets: ["custom_query"],
    domains: ["general", "ledger", "budgets", "cash", "customers", "suppliers"],
  },
  {
    key: "mysql",
    name: "MySQL",
    category: "data",
    description: "Query an internal MySQL database.",
    authType: "connection_string",
    datasets: ["custom_query"],
    domains: ["general", "ledger", "budgets", "cash", "customers", "suppliers"],
  },
  {
    key: "sqlserver",
    name: "Microsoft SQL Server",
    category: "data",
    description: "Query an internal SQL Server database.",
    authType: "connection_string",
    datasets: ["custom_query"],
    domains: ["general", "ledger", "budgets", "cash", "customers", "suppliers"],
  },
  {
    key: "snowflake",
    name: "Snowflake",
    category: "data",
    description: "Query a Snowflake warehouse.",
    authType: "connection_string",
    datasets: ["custom_query"],
    domains: ["general", "ledger", "budgets", "cash", "customers", "suppliers"],
  },
  {
    key: "bigquery",
    name: "Google BigQuery",
    category: "data",
    description: "Query a BigQuery dataset.",
    authType: "api_key",
    datasets: ["custom_query"],
    domains: ["general", "ledger", "budgets", "cash", "customers", "suppliers"],
  },
  {
    key: "redshift",
    name: "Amazon Redshift",
    category: "data",
    description: "Query a Redshift cluster.",
    authType: "connection_string",
    datasets: ["custom_query"],
    domains: ["general", "ledger", "budgets", "cash", "customers", "suppliers"],
  },
  {
    key: "rest_api",
    name: "REST API",
    category: "data",
    description: "Pull JSON from any REST endpoint.",
    authType: "api_key",
    datasets: ["custom_endpoint"],
    domains: ["general"],
  },
  {
    key: "graphql_api",
    name: "GraphQL API",
    category: "data",
    description: "Pull data from a GraphQL endpoint.",
    authType: "api_key",
    datasets: ["custom_query"],
    domains: ["general"],
  },
  {
    key: "sftp",
    name: "SFTP",
    category: "data",
    description: "Collect exports from a secure file server.",
    authType: "file_transfer",
    datasets: ["files"],
    domains: ["general"],
  },
  {
    key: "webhook",
    name: "Webhook",
    category: "data",
    description: "Receive pushed records at a generated endpoint.",
    authType: "api_key",
    datasets: ["events"],
    domains: ["general"],
  },
  {
    key: "custom_connector",
    name: "Custom connector",
    category: "data",
    description: "A connector built for your environment.",
    authType: "api_key",
    datasets: ["custom"],
    domains: ["general"],
  },

  // ── File storage (§16.5) ───────────────────────────────────────────────────
  {
    key: "google_drive",
    name: "Google Drive",
    category: "storage",
    description: "Import evidence files from Drive.",
    authType: "oauth2",
    datasets: ["files"],
    domains: ["general"],
  },
  {
    key: "onedrive",
    name: "Microsoft OneDrive",
    category: "storage",
    description: "Import evidence files from OneDrive.",
    authType: "oauth2",
    datasets: ["files"],
    domains: ["general"],
  },
  {
    key: "sharepoint",
    name: "SharePoint",
    category: "storage",
    description: "Import evidence from SharePoint document libraries.",
    authType: "oauth2",
    datasets: ["files"],
    domains: ["general"],
  },
  {
    key: "dropbox",
    name: "Dropbox",
    category: "storage",
    description: "Import evidence files from Dropbox.",
    authType: "oauth2",
    datasets: ["files"],
    domains: ["general"],
  },
  {
    key: "s3",
    name: "Amazon S3",
    category: "storage",
    description: "Import evidence from an S3 bucket.",
    authType: "api_key",
    datasets: ["files"],
    domains: ["general"],
  },
  {
    key: "azure_blob",
    name: "Azure Blob Storage",
    category: "storage",
    description: "Import evidence from Azure Blob Storage.",
    authType: "api_key",
    datasets: ["files"],
    domains: ["general"],
  },
] as const;

export const INTEGRATION_PROVIDER_KEYS = INTEGRATION_PROVIDERS.map((p) => p.key);

export function getProvider(key: string): IntegrationProvider | undefined {
  return INTEGRATION_PROVIDERS.find((p) => p.key === key);
}

export function providersByCategory(category: IntegrationCategory): IntegrationProvider[] {
  return INTEGRATION_PROVIDERS.filter((p) => p.category === category);
}

export const CATEGORY_LABELS: Record<IntegrationCategory, string> = {
  accounting: "Accounting systems",
  banking: "Banking",
  business: "Business systems",
  data: "Data platforms",
  storage: "File storage",
};
